[package]
name = "magic-collection-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sheets = "0.2.2"
clap = "3.1.6"
dotenv = "0.15.0"
envy = "0.4.2"
